apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-distro-config
  namespace: production
data:
  config_distro.py: |
    # Configuración estricta para Proxy Inverso en Kubernetes
    import os
    
    # Forzar a la app a correr bajo el subpath /pgadmin
    SCRIPT_NAME = '/pgadmin'
    
    # Activar el ProxyFix middleware de Flask internamente
    PROXY_X_FORW_ENBL = True
