apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-app-container
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/app-repo/my-app:latest
        ports:
        - containerPort: 8080
        # L2 Feature: Self-healing via Probes
       # livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
       # readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: LoadBalancer
  selector:
    app: mi-app-devops  # <--- Asegúrate que esto coincida con el 'labels' de tu deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # <--- El puerto donde corre tu app (main.py o server.js)
