apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: production
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        # Credenciales de acceso inicial para la interfaz web
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@ricardojop.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: ClaveSegura2026!
        # Prefijo lógico para que pgAdmin construya sus redirecciones y cargue los archivos estáticos (.js, .css)
        - name: PGADMIN_CONFIG_SCRIPT_NAME
          value: '"/pgadmin"'
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: production
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
