apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: production
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@ricardojop.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: ClaveSegura2026!
        # El juego de comillas dobles anidadas dentro de simples evita el SyntaxError
        - name: PGADMIN_CONFIG_SCRIPT_NAME
          value: '"/pgadmin"'
        # Desactivado para que no dependa de los snippets bloqueados del Ingress
        - name: PGADMIN_CONFIG_PROXY_X_FORW_ENBL
          value: "False"
        # Forzamos la raíz de la aplicación web de manera nativa
        - name: APPLICATION_ROOT
          value: /pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: production
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
