apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: production
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@ricardojop.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: ClaveSegura2026!
        # Fuerza el prefijo de la URL. Ojo a las comillas triples/anidadas para evitar el SyntaxError en Python.
        - name: PGADMIN_CONFIG_SCRIPT_NAME
          value: '"/pgadmin"'
        # Obliga a pgAdmin a confiar en los encabezados que manda NGINX (X-Forwarded-For, etc.)
        - name: PGADMIN_CONFIG_PROXY_X_FORW_ENBL
          value: "True"
        # Le dice a los workers de Gunicorn cuántos proxies tiene enfrente (el Ingress es 1)
        - name: PGADMIN_CONFIG_PROXY_X_FORW_NUM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: production
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
